const state = [
  { name: "Andhra Pradesh", code: "state-001" },
  { name: "Arunachal Pradesh", code: "state-002" },
  { name: "Assam", code: "state-003" },
  { name: "Bihar", code: "state-004" },
  { name: "Chhattisgarh", code: "state-005" },
  { name: "Goa", code: "state-006" },
  { name: "Gujarat", code: "state-007" },
  { name: "Haryana", code: "state-008" },
  { name: "Himachal Pradesh", code: "state-009" },
  { name: "Jharkhand", code: "state-010" },
  { name: "Karnataka", code: "state-011" },
  { name: "Kerala", code: "state-012" },
  { name: "Maharashtra", code: "state-013" },
  { name: "Madhya Pradesh", code: "state-014" },
  { name: "Manipur", code: "state-015" },
  { name: "Meghalaya", code: "state-016" },
  { name: "Mizoram", code: "state-017" },
  { name: "Nagaland", code: "state-018" },
  { name: "Odisha", code: "state-019" },
  { name: "Punjab", code: "state-020" },
  { name: "Rajasthan", code: "state-021" },
  { name: "Sikkim", code: "state-022" },
  { name: "Tamil Nadu", code: "state-023" },
  { name: "Tripura", code: "state-024" },
  { name: "Telangana", code: "state-025" },
  { name: "Uttar Pradesh", code: "state-026" },
  { name: "Uttarakhand", code: "state-027" },
  { name: "West Bengal", code: "state-028" },
  { name: "Andaman & Nicobar (UT)", code: "state-029" },
  { name: "Chandigarh (UT)", code: "state-030" },
  { name: "Dadra & Nagar Haveli and Daman & Diu (UT)", code: "state-031" },
  { name: "Delhi [National Capital Territory (NCT)]", code: "state-032" },
  { name: "Jammu & Kashmir (UT)", code: "state-033" },
  { name: "Ladakh (UT)", code: "state-034" },
  { name: "Lakshadweep (UT)", code: "state-035" },
  { name: "Puducherry (UT)", code: "state-036" },
];

const district = [
  {
    state: "state-026",
    district: [
      "Agra",
      "Aligarh",
      "Ambedkar Nagar",
      "Amethi",
      "Amroha",
      "Auraiya",
      "Ayodhya",
      "Azamgarh",
      "Baghpat",
      "Bahraich",
      "Ballia",
      "Balrampur",
      "Banda",
      "Bara Banki",
      "Bareilly",
      "Basti",
      "Bhadohi",
      "Bijnor",
      "Budaun",
      "Bulandshahr",
      "Chandauli",
      "Chitrakoot",
      "Deoria",
      "Etah",
      "Etawah",
      "Ghazipur",
      "Gonda",
      "Gorakhpur",
      "Hamirpur",
      "Hapur",
      "Farrukhabad",
      "Fatehpur",
      "Firozabad",
      "Gautam Buddha Nagar",
      "Ghaziabad",
      "Hardoi",
      "Hathras",
      "Jalaun",
      "Jaunpur",
      "Jhansi",
      "Kannauj",
      "Kanpur Dehat",
      "Kanpur Nagar",
      "Kasganj",
      "Kaushambi",
      "Kheri",
      "Kushinagar",
      "Lalitpur",
      "Lucknow",
      "Mahoba",
      "Prayagraj",
      "Rae Bareli",
      "Rampur",
      "Saharanpur",
      "Sambhal",
      "Mahrajganj",
      "Mainpuri",
      "Mathura",
      "Mau",
      "Meerut",
      "Mirzapur",
      "Moradabad",
      "Muzaffarnagar",
      "Pilibhit",
      "Pratapgarh",
      "Sant Kabir Nagar",
      "Shahjahanpur",
      "Shamli",
      "Shrawasti",
      "Siddharthnagar",
      "Sitapur",
      "Sonbhadra",
      "Sultanpur",
      "Unnao",
      "Varanasi",
    ],
  },
];

const category = [];

const department = [{ state: "state-026", department: {} }];

export default { state, district, department, category };
