const state = [
  { label: "Select..." },
  { label: "Andhra Pradesh", value: "Andhra Pradesh" },
  { label: "Arunachal Pradesh", value: "Arunachal Pradesh" },
  { label: "Assam", value: "Assam" },
  { label: "Bihar", value: "Bihar" },
  { label: "Chhattisgarh", value: "Chhattisgarh" },
  { label: "Goa", value: "Goa" },
  { label: "Gujarat", value: "Gujarat" },
  { label: "Haryana", value: "Haryana" },
  { label: "Himachal Pradesh", value: "Himachal Pradesh" },
  { label: "Jharkhand", value: "Jharkhand" },
  { label: "Karnataka", value: "Karnataka" },
  { label: "Kerala", value: "Kerala" },
  { label: "Maharashtra", value: "Maharashtra" },
  { label: "Madhya Pradesh", value: "Madhya Pradesh" },
  { label: "Manipur", value: "Manipur" },
  { label: "Meghalaya", value: "Meghalaya" },
  { label: "Mizoram", value: "Mizoram" },
  { label: "Nagaland", value: "Nagaland" },
  { label: "Odisha", value: "Odisha" },
  { label: "Punjab", value: "Punjab" },
  { label: "Rajasthan", value: "Rajasthan" },
  { label: "Sikkim", value: "Sikkim" },
  { label: "Tamil Nadu", value: "Tamil Nadu" },
  { label: "Tripura", value: "Tripura" },
  { label: "Telangana", value: "Telangana" },
  { label: "Uttar Pradesh", value: "Uttar Pradesh" },
  { label: "Uttarakhand", value: "Uttarakhand" },
  { label: "West Bengal", value: "West Bengal" },
  {
    label: "Andaman & Nicobar (UT)",

    value: "Andaman & Nicobar (UT)",
  },
  { label: "Chandigarh (UT)", value: "Chandigarh (UT)" },
  {
    label: "Dadra & Nagar Haveli and Daman & Diu (UT)",

    value: "Dadra & Nagar Haveli and Daman & Diu (UT)",
  },
  {
    label: "Delhi [National Capital Territory (NCT)]",

    value: "Delhi [National Capital Territory (NCT)]",
  },
  {
    label: "Jammu & Kashmir (UT)",

    value: "Jammu & Kashmir (UT)",
  },
  { label: "Ladakh (UT)", value: "Ladakh (UT)" },
  { label: "Lakshadweep (UT)", value: "Lakshadweep (UT)" },
  { label: "Puducherry (UT)", value: "Puducherry (UT)" },
];

const district = [
  {
    "Uttar Pradesh": [
      { label: "Agra", value: "Agra" },
      { label: "Aligarh", value: "Aligarh" },
      { label: "Ambedkar Nagar", value: "Ambedkar Nagar" },
      { label: "Amethi", value: "Amethi" },
      { label: "Amroha", value: "Amroha" },
      { label: "Auraiya", value: "Auraiya" },
      { label: "Ayodhya", value: "Ayodhya" },
      { label: "Azamgarh", value: "Azamgarh" },
      { label: "Baghpat", value: "Baghpat" },
      { label: "Bahraich", value: "Bahraich" },
      { label: "Ballia", value: "Ballia" },
      { label: "Balrampur", value: "Balrampur" },
      { label: "Banda", value: "Banda" },
      { label: "Bara Banki", value: "Bara Banki" },
      { label: "Bareilly", value: "Bareilly" },
      { label: "Basti", value: "Basti" },
      { label: "Bhadohi", value: "Bhadohi" },
      { label: "Bijnor", value: "Bijnor" },
      { label: "Budaun", value: "Budaun" },
      { label: "Bulandshahr", value: "Bulandshahr" },
      { label: "Chandauli", value: "Chandauli" },
      { label: "Chitrakoot", value: "Chitrakoot" },
      { label: "Deoria", value: "Deoria" },
      { label: "Etah", value: "Etah" },
      { label: "Etawah", value: "Etawah" },
      { label: "Ghazipur", value: "Ghazipur" },
      { label: "Gonda", value: "Gonda" },
      { label: "Gorakhpur", value: "Gorakhpur" },
      { label: "Hamirpur", value: "Hamirpur" },
      { label: "Hapur", value: "Hapur" },
      { label: "Farrukhabad", value: "Farrukhabad" },
      { label: "Fatehpur", value: "Fatehpur" },
      { label: "Firozabad", value: "Firozabad" },
      { label: "Gautam Buddha Nagar", value: "Gautam Buddha Nagar" },
      { label: "Ghaziabad", value: "Ghaziabad" },
      { label: "Hardoi", value: "Hardoi" },
      { label: "Hathras", value: "Hathras" },
      { label: "Jalaun", value: "Jalaun" },
      { label: "Jaunpur", value: "Jaunpur" },
      { label: "Jhansi", value: "Jhansi" },
      { label: "Kannauj", value: "Kannauj" },
      { label: "Kanpur Dehat", value: "Kanpur Dehat" },
      { label: "Kanpur Nagar", value: "Kanpur Nagar" },
      { label: "Kasganj", value: "Kasganj" },
      { label: "Kaushambi", value: "Kaushambi" },
      { label: "Kheri", value: "Kheri" },
      { label: "Kushinagar", value: "Kushinagar" },
      { label: "Lalitpur", value: "Lalitpur" },
      { label: "Lucknow", value: "Lucknow" },
      { label: "Mahoba", value: "Mahoba" },
      { label: "Prayagraj", value: "Prayagraj" },
      { label: "Rae Bareli", value: "Rae Bareli" },
      { label: "Rampur", value: "Rampur" },
      { label: "Saharanpur", value: "Saharanpur" },
      { label: "Sambhal", value: "Sambhal" },
      { label: "Mahrajganj", value: "Mahrajganj" },
      { label: "Mainpuri", value: "Mainpuri" },
      { label: "Mathura", value: "Mathura" },
      { label: "Mau", value: "Mau" },
      { label: "Meerut", value: "Meerut" },
      { label: "Mirzapur", value: "Mirzapur" },
      { label: "Moradabad", value: "Moradabad" },
      { label: "Muzaffarnagar", value: "Muzaffarnagar" },
      { label: "Pilibhit", value: "Pilibhit" },
      { label: "Pratapgarh", value: "Pratapgarh" },
      { label: "Sant Kabir Nagar", value: "Sant Kabir Nagar" },
      { label: "Shahjahanpur", value: "Shahjahanpur" },
      { label: "Shamli", value: "Shamli" },
      { label: "Shrawasti", value: "Shrawasti" },
      { label: "Siddharthnagar", value: "Siddharthnagar" },
      { label: "Sitapur", value: "Sitapur" },
      { label: "Sonbhadra", value: "Sonbhadra" },
      { label: "Sultanpur", value: "Sultanpur" },
      { label: "Unnao", value: "Unnao" },
      { label: "Varanasi", value: "Varanasi" },
    ],
  },
];

const category = [];

const department = [{ state: "state-026", department: {} }];

export default { state, district, department, category };
